export type BankQuestion = {
  text: string;
  options: string[];
  correctAnswerIndex: number;
};

export type Category = "math" | "tech" | "general";
export type Difficulty = "easy" | "medium" | "hard";

export const questionBank: Record<Category, Record<Difficulty, BankQuestion[]>> = {
  math: {
    easy: [
      { text: "What is 5 + 7?", options: ["10", "11", "12", "13"], correctAnswerIndex: 2 },
      { text: "What is 3 × 6?", options: ["15", "18", "21", "24"], correctAnswerIndex: 1 },
      { text: "What is 20 ÷ 4?", options: ["4", "5", "6", "7"], correctAnswerIndex: 1 },
      { text: "What is 9 - 4?", options: ["3", "4", "5", "6"], correctAnswerIndex: 2 },
      { text: "What is 8 + 3?", options: ["9", "10", "11", "12"], correctAnswerIndex: 2 },
      { text: "What is 7 × 2?", options: ["12", "13", "14", "15"], correctAnswerIndex: 2 },
      { text: "What is 15 ÷ 3?", options: ["3", "4", "5", "6"], correctAnswerIndex: 2 },
      { text: "What is 100 - 37?", options: ["53", "63", "73", "83"], correctAnswerIndex: 1 },
      { text: "What is 6 × 6?", options: ["30", "32", "36", "38"], correctAnswerIndex: 2 },
      { text: "What is 50 + 25?", options: ["65", "70", "75", "80"], correctAnswerIndex: 2 },
      { text: "What is 4²?", options: ["8", "12", "16", "20"], correctAnswerIndex: 2 },
      { text: "What is 12 ÷ 4?", options: ["2", "3", "4", "5"], correctAnswerIndex: 1 },
      { text: "What is 9 + 8?", options: ["15", "16", "17", "18"], correctAnswerIndex: 2 },
      { text: "What is 10% of 200?", options: ["10", "15", "20", "25"], correctAnswerIndex: 2 },
      { text: "What is 18 - 9?", options: ["7", "8", "9", "10"], correctAnswerIndex: 2 },
      { text: "How many sides does a hexagon have?", options: ["5", "6", "7", "8"], correctAnswerIndex: 1 },
      { text: "What is 2³?", options: ["4", "6", "8", "10"], correctAnswerIndex: 2 },
      { text: "What is 14 ÷ 2?", options: ["5", "6", "7", "8"], correctAnswerIndex: 2 },
      { text: "What is 11 × 11?", options: ["111", "121", "131", "141"], correctAnswerIndex: 1 },
      { text: "What is 3 + 3 + 3 + 3?", options: ["9", "12", "15", "18"], correctAnswerIndex: 1 },
    ],
    medium: [
      { text: "What is 15% of 80?", options: ["10", "12", "14", "16"], correctAnswerIndex: 1 },
      { text: "What is √144?", options: ["10", "11", "12", "13"], correctAnswerIndex: 2 },
      { text: "What is 2⁸?", options: ["128", "256", "512", "1024"], correctAnswerIndex: 1 },
      { text: "What is 7³?", options: ["243", "343", "443", "543"], correctAnswerIndex: 1 },
      { text: "What is 15% of 200?", options: ["25", "30", "35", "40"], correctAnswerIndex: 1 },
      { text: "A triangle has angles 40° and 70°. What is the third angle?", options: ["60°", "65°", "70°", "80°"], correctAnswerIndex: 2 },
      { text: "What is the area of a rectangle 5m × 12m?", options: ["50m²", "55m²", "60m²", "65m²"], correctAnswerIndex: 2 },
      { text: "What is 3/4 as a decimal?", options: ["0.5", "0.65", "0.75", "0.85"], correctAnswerIndex: 2 },
      { text: "What is the LCM of 4 and 6?", options: ["8", "10", "12", "14"], correctAnswerIndex: 2 },
      { text: "What is 25² ?", options: ["525", "575", "625", "675"], correctAnswerIndex: 2 },
      { text: "What is -3 × -5?", options: ["-15", "-8", "8", "15"], correctAnswerIndex: 3 },
      { text: "What is the perimeter of a square with side 8cm?", options: ["24cm", "28cm", "32cm", "36cm"], correctAnswerIndex: 2 },
      { text: "How many degrees are in a full circle?", options: ["180", "270", "360", "420"], correctAnswerIndex: 2 },
      { text: "What is 40% of 150?", options: ["45", "55", "60", "65"], correctAnswerIndex: 2 },
      { text: "If x + 5 = 12, what is x?", options: ["5", "6", "7", "8"], correctAnswerIndex: 2 },
      { text: "What is the GCD of 12 and 18?", options: ["3", "4", "6", "9"], correctAnswerIndex: 2 },
      { text: "What is 0.2 × 0.3?", options: ["0.005", "0.006", "0.05", "0.06"], correctAnswerIndex: 3 },
      { text: "What is 5! (5 factorial)?", options: ["60", "100", "120", "150"], correctAnswerIndex: 2 },
      { text: "What is the circumference of a circle with radius 7 (use π ≈ 22/7)?", options: ["38", "42", "44", "48"], correctAnswerIndex: 2 },
      { text: "If 2x = 18, what is x?", options: ["6", "7", "8", "9"], correctAnswerIndex: 3 },
    ],
    hard: [
      { text: "What is the derivative of x²?", options: ["x", "2x", "2x²", "x/2"], correctAnswerIndex: 1 },
      { text: "What is log₂(64)?", options: ["4", "5", "6", "7"], correctAnswerIndex: 2 },
      { text: "What is the sum of interior angles of a pentagon?", options: ["360°", "450°", "540°", "630°"], correctAnswerIndex: 2 },
      { text: "What is the integral of 2x dx?", options: ["x", "x²", "2x²", "x² + C"], correctAnswerIndex: 3 },
      { text: "What is the value of sin(90°)?", options: ["0", "0.5", "1", "√2/2"], correctAnswerIndex: 2 },
      { text: "How many prime numbers are between 1 and 20?", options: ["6", "7", "8", "9"], correctAnswerIndex: 2 },
      { text: "What is the quadratic formula solution for x² - 5x + 6 = 0?", options: ["x=1,6", "x=2,3", "x=2,4", "x=3,4"], correctAnswerIndex: 1 },
      { text: "What is the value of e (Euler's number) to 2 decimal places?", options: ["2.51", "2.61", "2.71", "2.81"], correctAnswerIndex: 2 },
      { text: "What is 1000 in binary?", options: ["0b01000", "0b01100", "0b10000", "0b11000"], correctAnswerIndex: 0 },
      { text: "What is the nth term of the Fibonacci sequence starting 1,1,2,3,5...? What is the 8th term?", options: ["18", "21", "23", "25"], correctAnswerIndex: 1 },
      { text: "What is the determinant of [[1,2],[3,4]]?", options: ["-4", "-2", "2", "4"], correctAnswerIndex: 1 },
      { text: "What is lim(x→0) sin(x)/x?", options: ["0", "π", "1", "∞"], correctAnswerIndex: 2 },
      { text: "If a matrix is 3×4 and another is 4×5, what is the size of their product?", options: ["3×5", "4×4", "5×3", "3×4"], correctAnswerIndex: 0 },
      { text: "What is the sum of the first 100 natural numbers?", options: ["4950", "5000", "5050", "5100"], correctAnswerIndex: 2 },
      { text: "What is tan(45°)?", options: ["0", "0.5", "1", "√3"], correctAnswerIndex: 2 },
      { text: "What is the value of cos(0°)?", options: ["0", "0.5", "1", "√2/2"], correctAnswerIndex: 2 },
      { text: "Solve: 3x + 2y = 12, x = 2. What is y?", options: ["2", "3", "4", "5"], correctAnswerIndex: 1 },
      { text: "What is the perimeter formula of a circle (circumference)?", options: ["πr", "πr²", "2πr", "2πr²"], correctAnswerIndex: 2 },
      { text: "What is the complex number i²?", options: ["1", "-1", "i", "-i"], correctAnswerIndex: 1 },
      { text: "What is the area of a triangle with base 10 and height 6?", options: ["20", "30", "40", "60"], correctAnswerIndex: 1 },
    ],
  },
  tech: {
    easy: [
      { text: "What does HTML stand for?", options: ["Hyper Text Markup Language", "High Tech Modern Language", "Hyperlink Text Markup Language", "Home Tool Markup Language"], correctAnswerIndex: 0 },
      { text: "What does CSS stand for?", options: ["Computer Style Sheets", "Cascading Style Sheets", "Creative Style Syntax", "Coded Style System"], correctAnswerIndex: 1 },
      { text: "Which of these is a programming language?", options: ["HTTP", "HTML", "Python", "CSS"], correctAnswerIndex: 2 },
      { text: "What does 'URL' stand for?", options: ["Universal Resource Locator", "Uniform Resource Locator", "Unified Record Locator", "Universal Record Link"], correctAnswerIndex: 1 },
      { text: "What does CPU stand for?", options: ["Central Processing Unit", "Core Processing Unit", "Central Program Utility", "Computer Processing Utility"], correctAnswerIndex: 0 },
      { text: "What does RAM stand for?", options: ["Random Access Memory", "Read-Only Access Memory", "Rapid Application Memory", "Remote Access Module"], correctAnswerIndex: 0 },
      { text: "What symbol is used in email addresses?", options: ["#", "%", "@", "&"], correctAnswerIndex: 2 },
      { text: "What does 'HTTP' stand for?", options: ["HyperText Transfer Protocol", "Hybrid Transfer Text Protocol", "HyperText Transmission Plan", "High-Tech Transfer Protocol"], correctAnswerIndex: 0 },
      { text: "Which company created the iPhone?", options: ["Samsung", "Google", "Apple", "Microsoft"], correctAnswerIndex: 2 },
      { text: "What is the main function of a web browser?", options: ["Store files", "Play games", "Access websites", "Edit photos"], correctAnswerIndex: 2 },
      { text: "What does 'Wi-Fi' primarily enable?", options: ["Wired internet", "Wireless internet", "Bluetooth connection", "Satellite TV"], correctAnswerIndex: 1 },
      { text: "Which of these is a search engine?", options: ["YouTube", "Facebook", "Google", "Twitter"], correctAnswerIndex: 2 },
      { text: "What does 'OS' stand for in computing?", options: ["Online System", "Open Source", "Operating System", "Output Server"], correctAnswerIndex: 2 },
      { text: "What is a 'byte' made of?", options: ["4 bits", "8 bits", "16 bits", "32 bits"], correctAnswerIndex: 1 },
      { text: "What programming language runs in web browsers natively?", options: ["Python", "Java", "JavaScript", "PHP"], correctAnswerIndex: 2 },
      { text: "What does 'PDF' stand for?", options: ["Page Document Format", "Portable Document Format", "Print Data Format", "Public Data File"], correctAnswerIndex: 1 },
      { text: "Which of these is NOT a web browser?", options: ["Chrome", "Firefox", "Photoshop", "Safari"], correctAnswerIndex: 2 },
      { text: "What is the shortcut to copy text on most computers?", options: ["Ctrl+V", "Ctrl+X", "Ctrl+C", "Ctrl+Z"], correctAnswerIndex: 2 },
      { text: "What does USB stand for?", options: ["Universal Serial Bus", "Unified System Board", "Universal Storage Board", "Ultra Speed Bus"], correctAnswerIndex: 0 },
      { text: "What language is primarily used to style web pages?", options: ["HTML", "CSS", "SQL", "XML"], correctAnswerIndex: 1 },
    ],
    medium: [
      { text: "What does 'API' stand for?", options: ["Application Programming Interface", "Advanced Programming Integration", "Automated Program Instance", "Application Process Interface"], correctAnswerIndex: 0 },
      { text: "What does 'SQL' stand for?", options: ["Standard Query Language", "Structured Query Language", "Simple Query Language", "System Query Logic"], correctAnswerIndex: 1 },
      { text: "Which data structure uses LIFO?", options: ["Queue", "Stack", "Tree", "Graph"], correctAnswerIndex: 1 },
      { text: "What is the time complexity of binary search?", options: ["O(n)", "O(n²)", "O(log n)", "O(1)"], correctAnswerIndex: 2 },
      { text: "What does 'DNS' stand for?", options: ["Domain Name Server", "Domain Name System", "Digital Network Service", "Dynamic Name System"], correctAnswerIndex: 1 },
      { text: "Which protocol is used to send email?", options: ["FTP", "HTTP", "SMTP", "POP3"], correctAnswerIndex: 2 },
      { text: "In Git, which command creates a new branch?", options: ["git new", "git branch", "git create", "git fork"], correctAnswerIndex: 1 },
      { text: "What does 'OOP' stand for?", options: ["Object Oriented Processing", "Object Oriented Programming", "Ordered Object Processing", "Open Object Protocol"], correctAnswerIndex: 1 },
      { text: "What is the default port for HTTPS?", options: ["80", "21", "443", "8080"], correctAnswerIndex: 2 },
      { text: "What type of language is Python?", options: ["Compiled only", "Interpreted only", "Machine language", "Assembly language"], correctAnswerIndex: 1 },
      { text: "What does 'JSON' stand for?", options: ["Java Standard Object Notation", "JavaScript Object Notation", "Java Serialized Object Node", "JavaScript Simple Object Node"], correctAnswerIndex: 1 },
      { text: "Which sorting algorithm has the best average-case time complexity?", options: ["Bubble Sort", "Quick Sort", "Insertion Sort", "Selection Sort"], correctAnswerIndex: 1 },
      { text: "What is a REST API?", options: ["A type of database", "An architectural style for APIs", "A programming language", "A file format"], correctAnswerIndex: 1 },
      { text: "What does 'npm' stand for?", options: ["Node Package Manager", "New Program Module", "Node Process Monitor", "Network Package Manager"], correctAnswerIndex: 0 },
      { text: "What does 'HTML5' refer to?", options: ["The 5th version of HTML", "A JavaScript framework", "A CSS framework", "A database language"], correctAnswerIndex: 0 },
      { text: "What keyword declares a constant in JavaScript?", options: ["var", "let", "const", "static"], correctAnswerIndex: 2 },
      { text: "What does 'SSL' stand for?", options: ["Secure Socket Layer", "Simple Secure Login", "Site Security Layer", "Standard Security Link"], correctAnswerIndex: 0 },
      { text: "What is a primary key in a database?", options: ["Any column", "A unique identifier for a row", "The first column in a table", "A foreign key"], correctAnswerIndex: 1 },
      { text: "What is the purpose of a CDN?", options: ["Store databases", "Deliver content faster", "Create backups", "Write code"], correctAnswerIndex: 1 },
      { text: "Which of these is a NoSQL database?", options: ["MySQL", "PostgreSQL", "MongoDB", "SQLite"], correctAnswerIndex: 2 },
    ],
    hard: [
      { text: "What design pattern does React's Context API implement?", options: ["Observer", "Singleton", "Provider/Consumer", "Factory"], correctAnswerIndex: 2 },
      { text: "What is the CAP theorem in distributed systems?", options: ["Consistency, Availability, Partition tolerance", "Cache, API, Protocol", "Concurrency, Atomicity, Parallelism", "Compile, Assemble, Package"], correctAnswerIndex: 0 },
      { text: "What is Big O notation used to describe?", options: ["Code size", "Algorithm performance", "Database size", "Memory usage"], correctAnswerIndex: 1 },
      { text: "What algorithm is used in Dijkstra's shortest path?", options: ["Depth-first search", "Greedy algorithm", "Dynamic programming", "Divide and conquer"], correctAnswerIndex: 1 },
      { text: "What is a closure in JavaScript?", options: ["A way to end a program", "A function with access to its outer scope", "A type of loop", "An arrow function"], correctAnswerIndex: 1 },
      { text: "What is the purpose of the 'virtual DOM' in React?", options: ["Direct DOM manipulation", "Efficient UI updates", "Server-side rendering", "State management"], correctAnswerIndex: 1 },
      { text: "What does 'ACID' stand for in databases?", options: ["Atomic, Consistent, Isolated, Durable", "Available, Clustered, Independent, Durable", "Atomic, Compressed, Indexed, Dynamic", "Asynchronous, Concurrent, Integrated, Distributed"], correctAnswerIndex: 0 },
      { text: "What is 'memoization' in programming?", options: ["A way to delete cache", "Caching function results for repeated calls", "A type of recursion", "A memory allocation method"], correctAnswerIndex: 1 },
      { text: "What does TCP stand for?", options: ["Transfer Control Protocol", "Transmission Control Protocol", "Technology Connection Protocol", "Transport Configuration Protocol"], correctAnswerIndex: 1 },
      { text: "What is the difference between `==` and `===` in JavaScript?", options: ["No difference", "=== checks type and value, == only checks value", "== is stricter", "=== only works for strings"], correctAnswerIndex: 1 },
      { text: "What is the time complexity of accessing an element in a hash table?", options: ["O(log n)", "O(n)", "O(1)", "O(n log n)"], correctAnswerIndex: 2 },
      { text: "What is 'event bubbling' in JavaScript?", options: ["Creating events", "Events propagating from child to parent", "Events going from parent to child", "A type of animation"], correctAnswerIndex: 1 },
      { text: "What is a microservices architecture?", options: ["A single large application", "Multiple small independent services", "A desktop application model", "A type of database design"], correctAnswerIndex: 1 },
      { text: "What does CORS stand for?", options: ["Cross-Origin Resource Sharing", "Central Origin Request System", "Cross-Object Resource Standard", "Concurrent Origin Resource Service"], correctAnswerIndex: 0 },
      { text: "What is the purpose of Docker?", options: ["Code editing", "Containerizing applications", "Database management", "Network configuration"], correctAnswerIndex: 1 },
      { text: "What is a deadlock in computing?", options: ["A crashed program", "Two processes blocking each other indefinitely", "A memory leak", "An infinite loop"], correctAnswerIndex: 1 },
      { text: "What is polymorphism in OOP?", options: ["Multiple inheritance", "Objects of different types treated as a common type", "A type of recursion", "Hiding data"], correctAnswerIndex: 1 },
      { text: "What is the difference between process and thread?", options: ["They are the same", "Threads share memory within a process", "Processes are smaller than threads", "Threads run on separate CPUs"], correctAnswerIndex: 1 },
      { text: "What is a JWT used for?", options: ["Database queries", "Secure information transmission", "CSS styling", "HTML templating"], correctAnswerIndex: 1 },
      { text: "What is the purpose of an index in a database?", options: ["Store data", "Speed up data retrieval", "Back up data", "Encrypt data"], correctAnswerIndex: 1 },
    ],
  },
  general: {
    easy: [
      { text: "What is the capital of France?", options: ["Berlin", "Madrid", "Paris", "Rome"], correctAnswerIndex: 2 },
      { text: "How many continents are there on Earth?", options: ["5", "6", "7", "8"], correctAnswerIndex: 2 },
      { text: "What is the largest planet in our solar system?", options: ["Saturn", "Jupiter", "Neptune", "Uranus"], correctAnswerIndex: 1 },
      { text: "Which animal is known as the 'King of the Jungle'?", options: ["Tiger", "Elephant", "Lion", "Cheetah"], correctAnswerIndex: 2 },
      { text: "How many days are in a leap year?", options: ["364", "365", "366", "367"], correctAnswerIndex: 2 },
      { text: "What color is the sky on a clear day?", options: ["Green", "Blue", "Yellow", "White"], correctAnswerIndex: 1 },
      { text: "How many letters are in the English alphabet?", options: ["24", "25", "26", "27"], correctAnswerIndex: 2 },
      { text: "What is the boiling point of water in Celsius?", options: ["90°C", "95°C", "100°C", "110°C"], correctAnswerIndex: 2 },
      { text: "Who wrote 'Romeo and Juliet'?", options: ["Charles Dickens", "William Shakespeare", "Mark Twain", "Jane Austen"], correctAnswerIndex: 1 },
      { text: "How many sides does a triangle have?", options: ["2", "3", "4", "5"], correctAnswerIndex: 1 },
      { text: "What is the largest ocean on Earth?", options: ["Atlantic", "Indian", "Arctic", "Pacific"], correctAnswerIndex: 3 },
      { text: "Which planet is closest to the Sun?", options: ["Earth", "Venus", "Mercury", "Mars"], correctAnswerIndex: 2 },
      { text: "What language do they speak in Brazil?", options: ["Spanish", "English", "Portuguese", "French"], correctAnswerIndex: 2 },
      { text: "How many hours are in a day?", options: ["20", "22", "24", "26"], correctAnswerIndex: 2 },
      { text: "What is H₂O commonly known as?", options: ["Salt", "Sugar", "Water", "Oil"], correctAnswerIndex: 2 },
      { text: "Which is the tallest mountain in the world?", options: ["K2", "Mount Everest", "Kangchenjunga", "Mont Blanc"], correctAnswerIndex: 1 },
      { text: "What is the capital of Japan?", options: ["Beijing", "Seoul", "Tokyo", "Bangkok"], correctAnswerIndex: 2 },
      { text: "How many months are in a year?", options: ["10", "11", "12", "13"], correctAnswerIndex: 2 },
      { text: "What color do you get when you mix red and white?", options: ["Orange", "Purple", "Pink", "Yellow"], correctAnswerIndex: 2 },
      { text: "Which instrument has black and white keys?", options: ["Guitar", "Violin", "Piano", "Drums"], correctAnswerIndex: 2 },
    ],
    medium: [
      { text: "What is the chemical symbol for gold?", options: ["Go", "Gd", "Au", "Ag"], correctAnswerIndex: 2 },
      { text: "What year did World War II end?", options: ["1943", "1944", "1945", "1946"], correctAnswerIndex: 2 },
      { text: "How many bones are in the adult human body?", options: ["186", "196", "206", "216"], correctAnswerIndex: 2 },
      { text: "What is the speed of light (approx) in km/s?", options: ["100,000", "200,000", "300,000", "400,000"], correctAnswerIndex: 2 },
      { text: "Which element has the symbol 'O'?", options: ["Osmium", "Oxygen", "Oganesson", "Oxide"], correctAnswerIndex: 1 },
      { text: "Who painted the Mona Lisa?", options: ["Michelangelo", "Raphael", "Leonardo da Vinci", "Picasso"], correctAnswerIndex: 2 },
      { text: "What is the longest river in the world?", options: ["Amazon", "Yangtze", "Mississippi", "Nile"], correctAnswerIndex: 3 },
      { text: "What gas do plants absorb from the air?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Helium"], correctAnswerIndex: 2 },
      { text: "Which country invented pizza?", options: ["France", "Spain", "Italy", "Greece"], correctAnswerIndex: 2 },
      { text: "What is the hardest natural substance on Earth?", options: ["Gold", "Iron", "Diamond", "Quartz"], correctAnswerIndex: 2 },
      { text: "What does DNA stand for?", options: ["Deoxyribonucleic Acid", "Dynamic Nuclear Acid", "Dextrose Nucleic Acid", "Double Nitrogen Atom"], correctAnswerIndex: 0 },
      { text: "Which country has the most natural lakes?", options: ["USA", "Russia", "Brazil", "Canada"], correctAnswerIndex: 3 },
      { text: "What is the closest star to Earth?", options: ["Sirius", "Betelgeuse", "The Sun", "Proxima Centauri"], correctAnswerIndex: 2 },
      { text: "What animal has the longest lifespan?", options: ["Elephant", "Tortoise", "Whale", "Human"], correctAnswerIndex: 1 },
      { text: "In which year did the first man land on the Moon?", options: ["1965", "1967", "1969", "1971"], correctAnswerIndex: 2 },
      { text: "What is the currency of Japan?", options: ["Yuan", "Won", "Yen", "Baht"], correctAnswerIndex: 2 },
      { text: "Which element is a diamond made of?", options: ["Silicon", "Carbon", "Calcium", "Nitrogen"], correctAnswerIndex: 1 },
      { text: "How many chambers does the human heart have?", options: ["2", "3", "4", "5"], correctAnswerIndex: 2 },
      { text: "Who discovered gravity by observing an apple fall?", options: ["Albert Einstein", "Isaac Newton", "Galileo Galilei", "Nikola Tesla"], correctAnswerIndex: 1 },
      { text: "What is the national language of Australia?", options: ["French", "Spanish", "English", "Mandarin"], correctAnswerIndex: 2 },
    ],
    hard: [
      { text: "What is the Schrödinger equation used to describe?", options: ["Gravity waves", "Quantum state of a system", "Electrical fields", "Chemical reactions"], correctAnswerIndex: 1 },
      { text: "Which country had the first written constitution?", options: ["France", "UK", "USA", "Greece"], correctAnswerIndex: 2 },
      { text: "What is the Coriolis effect?", options: ["Ocean wave patterns", "Deflection of moving objects due to Earth's rotation", "Atmospheric pressure changes", "Tidal forces"], correctAnswerIndex: 1 },
      { text: "What year did the Byzantine Empire fall?", options: ["1353", "1453", "1553", "1253"], correctAnswerIndex: 1 },
      { text: "What is the Higgs boson sometimes called?", options: ["God particle", "Devil particle", "Star particle", "Dark matter"], correctAnswerIndex: 0 },
      { text: "Which philosopher wrote 'Critique of Pure Reason'?", options: ["Nietzsche", "Hegel", "Kant", "Descartes"], correctAnswerIndex: 2 },
      { text: "What is the half-life of Carbon-14?", options: ["2,730 years", "4,230 years", "5,730 years", "7,730 years"], correctAnswerIndex: 2 },
      { text: "Which country produces the most coffee?", options: ["Colombia", "Ethiopia", "Vietnam", "Brazil"], correctAnswerIndex: 3 },
      { text: "What is the oldest known written language?", options: ["Egyptian hieroglyphs", "Sumerian cuneiform", "Sanskrit", "Chinese characters"], correctAnswerIndex: 1 },
      { text: "Who proposed the theory of continental drift?", options: ["Darwin", "Newton", "Wegener", "Einstein"], correctAnswerIndex: 2 },
      { text: "What is the most abundant gas in Earth's atmosphere?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"], correctAnswerIndex: 2 },
      { text: "What is the Fermi Paradox about?", options: ["Nuclear energy", "The apparent contradiction between alien life probability and lack of evidence", "Black hole formation", "Quantum entanglement"], correctAnswerIndex: 1 },
      { text: "In what year was the Magna Carta signed?", options: ["1115", "1215", "1315", "1415"], correctAnswerIndex: 1 },
      { text: "What is the world's largest desert (including cold deserts)?", options: ["Sahara", "Gobi", "Arabian", "Antarctic"], correctAnswerIndex: 3 },
      { text: "What did Alexander Fleming accidentally discover?", options: ["X-rays", "Penicillin", "DNA", "Aspirin"], correctAnswerIndex: 1 },
      { text: "What is the phonetic alphabet word for the letter 'W'?", options: ["Whiskey", "Wilson", "Warsaw", "Wolf"], correctAnswerIndex: 0 },
      { text: "Which planet has the most moons?", options: ["Jupiter", "Saturn", "Uranus", "Neptune"], correctAnswerIndex: 1 },
      { text: "What empire was ruled by Genghis Khan?", options: ["Roman Empire", "Ottoman Empire", "Mongol Empire", "Persian Empire"], correctAnswerIndex: 2 },
      { text: "What is the chemical formula for table salt?", options: ["NaCl", "KCl", "CaCl₂", "NaOH"], correctAnswerIndex: 0 },
      { text: "Which physicist is known for the theory of relativity?", options: ["Niels Bohr", "Max Planck", "Werner Heisenberg", "Albert Einstein"], correctAnswerIndex: 3 },
    ],
  },
};

export function getRandomQuestions(
  category: Category,
  difficulty: Difficulty,
  count: number = 10
): BankQuestion[] {
  const pool = questionBank[category][difficulty];
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}
